build-dev:
	docker build -t url-shortner-server-development:development .

build-local:
	docker build -t url-shortner-server-production:local .
	
build-production:
	docker build -t url-shortner-server-production:production .